#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
     touch $SERVICE_CONFIG
  fi

  config::load_file $SERVICE_NPM_CONFIG

  if [ -z "$SERVICE_NPM_HOST" ]; then
    inquirer::text "请输入 SERVICE_NPM_HOST:" value
    config::set SERVICE_NPM_HOST $value $SERVICE_NPM_CONFIG
  fi

  if [ -z "$SERVICE_NPM_PORT" ]; then
    inquirer::text "请输入 SERVICE_NPM_PORT:" value
    config::set SERVICE_NPM_PORT $value $SERVICE_NPM_CONFIG
  fi

  if [ -z "$SERVICE_NPM_ALY_OSS_ACCESS_KEY" ]; then
    inquirer::text "请输入 SERVICE_NPM_ALY_OSS_ACCESS_KEY:" value
    config::set SERVICE_NPM_ALY_OSS_ACCESS_KEY $value $SERVICE_NPM_CONFIG
  fi

  if [ -z "$SERVICE_NPM_ALY_OSS_ACCESS_SECRET" ]; then
    inquirer::text "请输入 SERVICE_NPM_ALY_OSS_ACCESS_SECRET:" value
    config::set SERVICE_NPM_ALY_OSS_ACCESS_SECRET $value $SERVICE_NPM_CONFIG
  fi

  if [ -z "$SERVICE_NPM_ALY_OSS_BUCKET" ]; then
    inquirer::text "请输入 SERVICE_NPM_ALY_OSS_BUCKET:" value
    config::set SERVICE_NPM_ALY_OSS_BUCKET $value $SERVICE_NPM_CONFIG
  fi
  
  if [ -z "$SERVICE_NPM_ALY_OSS_REGION" ]; then
    inquirer::text "请输入 SERVICE_NPM_ALY_OSS_REGION:" value
    config::set SERVICE_NPM_ALY_OSS_REGION $value $SERVICE_NPM_CONFIG
  fi

  if [ -z "$SERVICE_NPM_ADMIN_USERNAME" ]; then
    inquirer::text "请输入 SERVICE_NPM_ADMIN_USERNAME:" value
    config::set SERVICE_NPM_ADMIN_USERNAME $value $SERVICE_NPM_CONFIG
  fi

  if [ -z "$SERVICE_NPM_ADMIN_PASSWORD" ]; then
    inquirer::text "请输入 SERVICE_NPM_ADMIN_PASSWORD:" value
    config::set SERVICE_NPM_ADMIN_PASSWORD $value $SERVICE_NPM_CONFIG
  fi

  if [ -z "$SERVICE_NPM_USE_DOREAMON" ] && [ -z "$SERVICE_NPM_DOREAMON_CLIENT_ID" ]; then
    local choices=(
      "Yes"
      "No"
    )
    inquirer::select "Would you like to use Doreamon Login ?" choices value
    config::set SERVICE_NPM_USE_DOREAMON $value $SERVICE_NPM_CONFIG

    if [ "$value" == "Yes" ]; then
      if [ -z "$SERVICE_NPM_DOREAMON_CLIENT_ID" ]; then
        inquirer::text "请输入 SERVICE_NPM_DOREAMON_CLIENT_ID:" value
        config::set SERVICE_NPM_DOREAMON_CLIENT_ID $value $SERVICE_NPM_CONFIG
      fi

      if [ -z "$SERVICE_NPM_DOREAMON_CLIENT_SECRET" ]; then
        inquirer::text "请输入 SERVICE_NPM_DOREAMON_CLIENT_SECRET:" value
        config::set SERVICE_NPM_DOREAMON_CLIENT_SECRET $value $SERVICE_NPM_CONFIG
      fi
    fi
  fi

  # @TODO load again
  config::load_file $SERVICE_NPM_CONFIG

  # @TODO
  export SERVICE_NPM_HOST=$SERVICE_NPM_HOST
  export SERVICE_NPM_PORT=$SERVICE_NPM_PORT
  #
  export SERVICE_NPM_ALY_OSS_ACCESS_KEY=$SERVICE_NPM_ALY_OSS_ACCESS_KEY
  export SERVICE_NPM_ALY_OSS_ACCESS_SECRET=$SERVICE_NPM_ALY_OSS_ACCESS_SECRET
  export SERVICE_NPM_ALY_OSS_BUCKET=$SERVICE_NPM_ALY_OSS_BUCKET
  export SERVICE_NPM_ALY_OSS_REGION=$SERVICE_NPM_ALY_OSS_REGION
  #
  export SERVICE_NPM_ADMIN_USERNAME=$SERVICE_NPM_ADMIN_USERNAME
  export SERVICE_NPM_ADMIN_PASSWORD=$SERVICE_NPM_ADMIN_PASSWORD
  #
  export ROOT_URL=$ROOT_URL
}

check $@
