version: '3.7'

services:
  npm:
    restart: always
    image: whatwewant/verdaccio:${SERVICE_NPM_VERSION}
    user: root # "${SERVICE_NPM_UID}:${SERVICE_NPM_GID}"
    ports:
      - ${SERVICE_NPM_HOST}:${SERVICE_NPM_PORT}:4873
    environment:
      SECRET_TOKEN: ${SERVICE_NPM_SECRET_TOKEN}
      #
      ROOT_URL: ${SERVICE_NPM_ROOT_URL}
      #
      UPSTREAM_NPM_REGISTRY: https://${SERVICE_NPM_UPSTREAM_NPM_REGISTRY}
      #
      OSS_ACCESS_KEY: ${SERVICE_NPM_ALY_OSS_ACCESS_KEY} #Required
      OSS_ACCESS_SECRET: ${SERVICE_NPM_ALY_OSS_ACCESS_SECRET} #Required
      OSS_BUCKET: ${SERVICE_NPM_ALY_OSS_BUCKET} #Required
      OSS_REGION: ${SERVICE_NPM_ALY_OSS_REGION} #Required
      ADMIN_USERNAME: ${SERVICE_NPM_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${SERVICE_NPM_ADMIN_PASSWORD}
      # VERDACCIO_PORT: 4873
      DOREAMON_CLIENT_ID: ${SERVICE_NPM_DOREAMON_CLIENT_ID}
      DOREAMON_CLIENT_SECRET: ${SERVICE_NPM_DOREAMON_CLIENT_SECRET}
      #
      COMPANY: ${SERVICE_NPM_COMPANY}
      SCOPE: ${SERVICE_NPM_SCOPE}
    volumes:
      - ${SERVICE_CONFIGS}:/verdaccio/conf
      - ${SERVICE_DATA}/plugins:/verdaccio/plugins
      - ${SERVICE_DATA}/storage:/verdaccio/storage

networks:
  default:
    external: true
    name: compose-ingress
